# Generated by Django 3.1.1 on 2021-01-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_names', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
                ('v_watched', models.IntegerField(blank=True, null=True)),
                ('satisfied', models.BooleanField(default=False)),
                ('viewer_like', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
