# Generated by Django 3.1.1 on 2021-02-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='store/pdfs/')),
                ('cover', models.ImageField(upload_to='store/covers/')),
            ],
        ),
    ]
